### ISSUE TITLE
Cannot find version 8.0.mysql_aurora.3.02.2 for aurora-mysql (Service: Rds, Status Code: 400...) (RequestToken: da3d5693-9a5b-6bbb-da26-82b1eae584b9, HandlerErrorCode: InvalidRequest)

### ISSUE THREAD

**Issue by Oleksii909** [aws-samples/aws-cdk-localgov-drupal-fargate-efs-auroraserverlessv2#1]
When I perform command: `cdk deploy --all --require-approval never`

I am getting the error:
```
❌  DrupalCoreStackdrupal-9-localgov failed: Error: The stack named DrupalCoreStackdrupal-9-localgov failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Cannot find version 8.0.mysql_aurora.3.02.2 for aurora-mysql (Service: Rds, Status Code: 400, Request ID: cfed87d9-244a-44ee-a7ef-1a1ee9d3c338)" (RequestToken: da3d5693-9a5b-6bbb-da26-82b1eae584b9, HandlerErrorCode: InvalidRequest), Cannot set status to FAILED from status SUCCESS
    at FullCloudFormationDeployment.monitorDeployment (/Users/oleksiibondarenko/.npm/_npx/fa14b75510cd2922/node_modules/aws-cdk/lib/index.js:433:10615)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/oleksiibondarenko/.npm/_npx/fa14b75510cd2922/node_modules/aws-cdk/lib/index.js:436:200503)
    at async /Users/oleksiibondarenko/.npm/_npx/fa14b75510cd2922/node_modules/aws-cdk/lib/index.js:436:181341
```
    
# Here are the logs:

https://gist.github.com/Oleksii909/835af5100d957284f71a046cb518b3e8

**Comment by Oleksii909** [comment]
I think we need to update this repo to make it use one of the following db-engines:

```
[
    "8.0.mysql_aurora.3.03.0",
    "8.0.mysql_aurora.3.03.1",
    "8.0.mysql_aurora.3.03.2",
    "8.0.mysql_aurora.3.03.3",
    "8.0.mysql_aurora.3.04.0",
    "8.0.mysql_aurora.3.04.1",
    "8.0.mysql_aurora.3.04.2",
    "8.0.mysql_aurora.3.05.2",
    "8.0.mysql_aurora.3.06.0"
]
````
Cause the required `8.0.mysql_aurora.3.02.2` could not be found anymore. Check the available rds with the command: `  aws rds describe-db-engine-versions --engine aurora-mysql --query "DBEngineVersions[].EngineVersion"`

**Comment by chrisscudder** [comment]
Resolved with updated versions
